#! usr/bin/env php
<?php

namespace Creational\Builder;

require_once 'vendor/autoload.php';

$employee= new Master();
$employee->setBuilder(new DesktopBuilder());
$employee->getBuilder()
    ->setParam('hdd', 1024)
    ->setParam('ram', 8192)
    ->setParam('cpu', 3000)
    ->setParam('gpu', 5000)
    ->setParam('software', 'UNIX');

print_r($employee->build());
