#! usr/bin/env php
<?php

namespace Creational\Builder;

require_once 'vendor/autoload.php';

$master = new Master(new DesktopBuilder());
$master->getBuilder()
    ->addParam('hdd', 1024)
    ->addParam('ram', 8192)
    ->addParam('cpu', 3000)
    ->addParam('gpu', 5000)
    ->addParam('software', 'UNIX');

print_r($master->build());
